services:

  bot:
    build: ./services-python/bot
    depends_on:
      - redis_main
    env_file:
      - ./misc/dockerenvs/bot.env
    environment:
      - AUTH_HOST_IP=host.docker.internal
    networks:
      - yet_another_network
    
  redis_main:
    image: redis:7.4
    restart: always
    container_name: REDIS_MAIN
    env_file:
      - ./misc/dockerenvs/redis.env
    volumes:
      - redis_data
    ports:
      - "6379:6379"
    networks:
      - yet_another_network

volumes:
  redis_data:

networks:
  yet_another_network:
   driver: bridge

