
services:

  java-auth-service:
  
    build: ./microservices-java/auth-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
      - quarkus.datasource.jdbc.url="jdbc:postgresql://rc1a-bfu70ickst3dddjj.mdb.yandexcloud.net:6432,rc1b-f9lhyz1dv9xlf269.mdb.yandexcloud.net:6432,rc1b-kq6i0o1caufodow3.mdb.yandexcloud.net:6432/iotcloud_users?targetServerType=master&ssl=true&sslmode=verify-full&autoReconnect=true"
    command: 
    entrypoint: "|
                bash ./gradlew buildjava -jar 
                /auth_service/build/libs/app.jar"
    container_name: JAVA_AUTH


    