version: '3.7'

services:

  java-auth-service:
  
    build: ./microservices-java/auth-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
 
    entrypoint: "java -jar build/libs/app.jar"
    container_name: JAVA_AUTH

  
    
