name: "Deploy workflow"
on: [workflow_dispatch]

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Run in cloud
          uses: favware/ssh-remote-action@v1
          with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USER}}
            key: ${{secrets.SSH_PRIVATE_KEY}}
            command: |
              cd ${{ secrets.PROJECT_FOLDER }};
              git checkout main;
              git pull;
              sh misc/scripts/JavaBuildAll.sh;
              sh misc/scripts/StartAll.sh;
              
